"""Apply the design baseline verbatim.

Revision ID: 0001
Revises:
Create Date: 2026-09-26

Applies `db/baseline/00001_baseline.sql` — the design baseline — through
`Connection.exec_driver_sql()`, unmodified, as required by database spec §8.3 rule 1:
"The baseline is applied verbatim via `op.execute()`. Never autogenerated." (`exec_driver_sql`
is used instead of `op.execute()` specifically because it hands the raw multi-statement,
dollar-quoted script straight to the DBAPI with no SQLAlchemy statement compilation in the
way — exactly what a large, hand-written `.sql` file needs, and what `op.execute()` itself
does for a single statement under the hood.)

The baseline file wraps itself in its own `BEGIN;` / `COMMIT;`, because it is also meant to
be runnable directly with `psql -f`. Alembic already wraps this whole migration in its own
transaction, so those two lines are stripped before execution — nesting a `COMMIT;` inside
Alembic's transaction would end it early and leave Alembic's own bookkeeping (writing to
`alembic_version`) to run outside the transaction this revision is supposed to be atomic
with.

Every literal `%` in the file is doubled to `%%` before it reaches `psycopg`. This is not
optional: `psycopg` scans a query string for `%`-style placeholders even when no parameters
are given, so the baseline's own Postgres-side `%` syntax — `RAISE EXCEPTION '... %'`,
`format('%I %L')` — would otherwise raise `psycopg.ProgrammingError: incomplete
placeholder`. `psycopg` reduces `%%` back to a single `%` before the string ever reaches the
server, so what Postgres receives is byte-for-byte what the file says. (Found by actually
running this migration against a live PostgreSQL 15 container — see
`cineatelie/04-implementation/status-20260926-m0.md`.)

After the baseline creates `app_user` and `app_worker` as `NOLOGIN` roles with every grant
and RLS policy they need (schema section 15), this revision optionally gives them a
password — but only if `APP_USER_PASSWORD` / `APP_WORKER_PASSWORD` are set in the
environment, which is how local Docker Compose becomes usable end to end with a single
`alembic upgrade head` (db/README.md). Every other environment sets these passwords instead
through `db/roles/app_user.sql` and `db/roles/app_worker.sql`, deliberately, at a time of
its choosing — this revision runs exactly once, so it can never be the mechanism for
rotating a password later.
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from pathlib import Path

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_BASELINE_SQL_PATH = Path(__file__).resolve().parents[1] / "baseline" / "00001_baseline.sql"


def _strip_outer_transaction(sql: str) -> str:
    """Remove the file's own leading `BEGIN;` and trailing `COMMIT;` lines, so it can be
    executed inside Alembic's own transaction instead of nesting one. See module docstring.
    """
    lines = sql.splitlines()

    for i, line in enumerate(lines):
        if line.strip() == "BEGIN;":
            del lines[i]
            break
    else:
        raise RuntimeError(f"expected a standalone 'BEGIN;' line in {_BASELINE_SQL_PATH}")

    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == "COMMIT;":
            del lines[i]
            break
    else:
        raise RuntimeError(f"expected a standalone 'COMMIT;' line in {_BASELINE_SQL_PATH}")

    return "\n".join(lines)


def _escape_percent_for_psycopg(sql: str) -> str:
    """Double every literal `%` so `psycopg` doesn't parse it as the start of a
    placeholder (see module docstring). Safe unconditionally here: this file executes
    with zero bound parameters, so there is no real placeholder to preserve."""
    return sql.replace("%", "%%")


def _sql_string_literal(value: str) -> str:
    """Escape `value` as a single-quoted SQL string literal (doubling embedded quotes —
    the standard, driver-independent escaping, correct under PostgreSQL's default
    `standard_conforming_strings = on`). Used instead of a bound parameter so this
    statement executes the same way `exec_driver_sql` already runs the baseline above:
    one plain string, no driver-specific paramstyle to get right."""
    return "'" + value.replace("'", "''") + "'"


def _set_role_password_if_configured(conn, role: str, env_var: str) -> None:
    """Convenience for local development only — see module docstring.

    `role` is always one of the two literal strings passed by `upgrade()` below, never
    user input. The password is the only piece that comes from outside this file, read
    from the environment at execution time — it never appears as a literal in this file or
    anywhere in git history.
    """
    password = os.environ.get(env_var)
    if not password:
        return
    statement = f"ALTER ROLE {role} LOGIN PASSWORD {_sql_string_literal(password)}"
    # A generated dev password is unlikely to contain '%', but a hand-chosen one might —
    # escape unconditionally rather than assume.
    conn.exec_driver_sql(_escape_percent_for_psycopg(statement))


def upgrade() -> None:
    sql_text = _BASELINE_SQL_PATH.read_text(encoding="utf-8")
    sql_text = _strip_outer_transaction(sql_text)
    sql_text = _escape_percent_for_psycopg(sql_text)

    conn = op.get_bind()
    conn.exec_driver_sql(sql_text)

    _set_role_password_if_configured(conn, "app_user", "APP_USER_PASSWORD")
    _set_role_password_if_configured(conn, "app_worker", "APP_WORKER_PASSWORD")


def downgrade() -> None:
    raise RuntimeError(
        "The baseline has no downgrade. It is the beginning of history; reverting it means "
        "dropping the database, not running a migration (database spec §8.4 — every "
        "migration after this one is forward-only in the expand phase, and this one is not "
        "a migration in that sense at all)."
    )
